services:
  - type: web
    name: eduvault-web
    env: static
    buildCommand: cd src/EduVault.Web && npm install && npm run build
    staticPublishPath: ./src/EduVault.Web/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: eduvault-express
    env: node
    buildCommand: cd src/EduVault.Express && npm install
    startCommand: cd src/EduVault.Express && node server.js
