import { useState, useEffect } from 'react';
import { apiClient } from '../../../api/apiClient';
import { formatGrade } from '../../../utils/classUtils';

const FeeRulesTab = ({ classes = [], uniqueGradeClasses = [] }) => {
  const [feeRules, setFeeRules] = useState([]);
  const [studentsList, setStudentsList] = useState([]);
  const [loadingFees, setLoadingFees] = useState(false);
  const [feeComponents, setFeeComponents] = useState([]);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [feeForm, setFeeForm] = useState({
    name: '',
    type: 'class', // 'class', 'student'
    classId: '',
    grade: '',
    studentId: '',
    amount: '',
    installments: '1',
    submissionTime: 'Monthly'
  });

  const fetchFeeSetupData = async () => {
    try {
      const rulesRes = await apiClient.get('/billing/structures');
      setFeeRules(rulesRes.data);

      const studRes = await apiClient.get('/academics/students');
      setStudentsList(studRes.data);

      if (studRes.data.length > 0) {
        setFeeForm(f => ({ ...f, studentId: studRes.data[0].id }));
      }
    } catch (err) {
      console.error('Error fetching fee setup data:', err);
    }
  };

  useEffect(() => {
    fetchFeeSetupData();
  }, []);

  useEffect(() => {
    if (feeForm.classId && studentsList.length > 0) {
      const filtered = studentsList.filter(s => s.classId === feeForm.classId);
      if (filtered.length > 0) {
        setFeeForm(f => ({ ...f, studentId: filtered[0].id }));
      } else {
        setFeeForm(f => ({ ...f, studentId: '' }));
      }
    }
  }, [feeForm.classId, studentsList]);

  const handleCreateFeeRule = async (e) => {
    e.preventDefault();
    if (!feeForm.name || !feeForm.amount) {
      setError('Name and Amount are required.');
      return;
    }

    const totalVal = parseFloat(feeForm.amount);
    const sumComponents = feeComponents.reduce((sum, c) => sum + (parseFloat(c.amount) || 0), 0);
    const unassigned = totalVal - sumComponents;

    if (feeComponents.length > 0 && Math.abs(unassigned) >= 0.01) {
      setError('Sum of components must equal the Total Amount.');
      return;
    }

    const activeGradeGroup = uniqueGradeClasses.find(g => g.classIds.includes(feeForm.classId));
    const selectedClass = classes.find(c => c.id === feeForm.classId);
    const gradeStr = activeGradeGroup ? activeGradeGroup.formattedGrade : (selectedClass ? formatGrade(selectedClass.grade) : '');

    setLoadingFees(true);
    setError('');
    setSuccess('');
    try {
      await apiClient.post('/billing/structures', {
        name: feeForm.name.trim(),
        grade: gradeStr,
        studentId: feeForm.type === 'student' ? feeForm.studentId : null,
        amount: totalVal,
        frequency: feeForm.submissionTime,
        installments: parseInt(feeForm.installments),
        submissionTime: feeForm.submissionTime,
        breakdown: feeComponents.length > 0 ? JSON.stringify(feeComponents.map(c => ({ category: c.category, amount: parseFloat(c.amount) }))) : null
      });
      const secMsg = activeGradeGroup && activeGradeGroup.sections.length > 0 ? ` (Applies to all Sections: ${activeGradeGroup.sections.join(', ')})` : '';
      setSuccess(`🎉 Fee rule created once for ${gradeStr}${secMsg}! Invoices auto-generated.`);
      setFeeForm(f => ({ ...f, name: '', amount: '' }));
      setFeeComponents([]);
      fetchFeeSetupData();
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to create fee rule.');
    } finally {
      setLoadingFees(false);
    }
  };

  const handleDeleteFeeRule = async (id) => {
    if (!window.confirm('Are you sure you want to delete this fee rule? Any unpaid invoices generated by this rule will be deleted.')) return;
    setLoadingFees(true);
    setError('');
    setSuccess('');
    try {
      await apiClient.delete(`/billing/structures/${id}`);
      setSuccess('Fee rule deleted and associated unpaid invoices removed.');
      fetchFeeSetupData();
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to delete fee rule.');
    } finally {
      setLoadingFees(false);
    }
  };

  const totalVal = parseFloat(feeForm.amount) || 0;
  const sumComponents = feeComponents.reduce((sum, c) => sum + (parseFloat(c.amount) || 0), 0);
  const unassignedAmount = totalVal - sumComponents;
  const isBreakdownValid = feeComponents.length === 0 || Math.abs(unassignedAmount) < 0.01;

  return (
    <>
      {error && (
        <div className="bg-red-50 border border-red-200 text-red-600 text-sm font-semibold rounded-xl p-4 flex items-center justify-between mb-6">
          <span>{error}</span>
          <button onClick={() => setError('')} className="text-red-400 hover:text-red-600 font-bold ml-2">✕</button>
        </div>
      )}
      {success && (
        <div className="bg-emerald-50 border border-emerald-200 text-emerald-700 text-sm font-semibold rounded-xl p-4 flex items-center justify-between mb-6">
          <span>{success}</span>
          <button onClick={() => setSuccess('')} className="text-emerald-400 hover:text-emerald-600 font-bold ml-2">✕</button>
        </div>
      )}

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Create Fee Setup Rule Form */}
              <div className="card h-fit">
                <h3 className="font-display font-bold text-primary text-lg mb-2 flex items-center gap-2">
                  💰 Define Fee Rule
                </h3>
                <p className="text-gray-400 text-xs mb-4">Set up class-wide or student-specific fee structures and divide into installment steps.</p>

                <form onSubmit={handleCreateFeeRule} className="space-y-4">
                  <div>
                    <label className="block text-xs font-semibold text-gray-600 mb-1.5">Select Class *</label>
                    <select
                      value={(() => {
                        const active = uniqueGradeClasses.find(g => g.classIds.includes(feeForm.classId));
                        return active ? active.primaryClassId : feeForm.classId;
                      })()}
                      onChange={e => setFeeForm(f => ({ ...f, classId: e.target.value, studentId: '' }))}
                      className="input text-xs"
                      required
                    >
                      <option value="">Choose Class</option>
                      {uniqueGradeClasses.map(g => (
                        <option key={g.formattedGrade} value={g.primaryClassId}>
                          {g.formattedGrade} {g.sections.length > 0 ? `(Sections: ${g.sections.join(', ')})` : ''}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-gray-600 mb-1.5">Rule Scope *</label>
                    <div className="flex gap-4">
                      <label className="flex items-center gap-1.5 text-xs font-medium text-gray-700 cursor-pointer">
                        <input
                          type="radio"
                          checked={feeForm.type === 'class'}
                          onChange={() => setFeeForm(f => ({ ...f, type: 'class' }))}
                        />
                        Class-wide
                      </label>
                      <label className="flex items-center gap-1.5 text-xs font-medium text-gray-700 cursor-pointer">
                        <input
                          type="radio"
                          checked={feeForm.type === 'student'}
                          onChange={() => setFeeForm(f => ({ ...f, type: 'student' }))}
                        />
                        Specific Student
                      </label>
                    </div>
                  </div>

                  {feeForm.type === 'student' && (() => {
                    const activeGradeGroup = uniqueGradeClasses.find(g => g.classIds.includes(feeForm.classId));
                    const targetClassIds = activeGradeGroup ? activeGradeGroup.classIds : [feeForm.classId];
                    const gradeStudents = studentsList.filter(s => targetClassIds.includes(s.classId));
                    return (
                      <div>
                        <label className="block text-xs font-semibold text-gray-600 mb-1.5">Select Student *</label>
                        <select
                          value={feeForm.studentId}
                          onChange={e => setFeeForm(f => ({ ...f, studentId: e.target.value }))}
                          className="input text-xs"
                          required
                        >
                          <option value="">Choose Student</option>
                          {gradeStudents.map(s => (
                            <option key={s.id} value={s.id}>
                              {s.name} ({s.studentId})
                            </option>
                          ))}
                        </select>
                      </div>
                    );
                  })()}

                  {feeForm.classId && (() => {
                    const activeGradeGroup = uniqueGradeClasses.find(g => g.classIds.includes(feeForm.classId));
                    const targetClassIds = activeGradeGroup ? activeGradeGroup.classIds : [feeForm.classId];
                    const gradeStudents = studentsList.filter(s => targetClassIds.includes(s.classId));
                    return (
                      <div className="bg-gray-50/50 rounded-xl p-3 border border-gray-100 text-xs">
                        <div className="font-bold text-gray-500 mb-2 uppercase text-[10px]">
                          Students in selected class ({gradeStudents.length})
                        </div>
                        <div className="max-h-36 overflow-y-auto space-y-1.5 pr-1">
                          {gradeStudents.map(s => {
                            const isSelected = feeForm.type === 'student' && feeForm.studentId === s.id;
                            return (
                              <div key={s.id} className={`flex justify-between items-center px-2.5 py-1.5 rounded-lg border transition-all ${isSelected ? 'bg-indigo-50 border-indigo-200 font-bold text-primary' : 'bg-white border-gray-100'}`}>
                                <span>{s.name}</span>
                                <span className="text-[10px] text-gray-400 font-mono">{s.studentId}</span>
                              </div>
                            );
                          })}
                          {gradeStudents.length === 0 && (
                            <div className="text-gray-400 italic text-2xs text-center py-2">No students enrolled in this class.</div>
                          )}
                        </div>
                      </div>
                    );
                  })()}

                  <div>
                    <label className="block text-xs font-semibold text-gray-600 mb-1.5">Fee Name *</label>
                    <input
                      required
                      value={feeForm.name}
                      onChange={e => setFeeForm(f => ({ ...f, name: e.target.value }))}
                      placeholder="e.g. Tuition Fee Term 1"
                      className="input text-sm"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-gray-600 mb-1.5">Total Amount (₹) *</label>
                    <input
                      type="number"
                      required
                      value={feeForm.amount}
                      onChange={e => setFeeForm(f => ({ ...f, amount: e.target.value }))}
                      placeholder="e.g. 15000"
                      className="input text-sm"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-gray-600 mb-1.5">Divide into Stagered Steps (Installments) *</label>
                    <select
                      value={feeForm.installments}
                      onChange={e => setFeeForm(f => ({ ...f, installments: e.target.value }))}
                      className="input text-xs"
                      required
                    >
                      {[1, 2, 3, 4, 5, 6, 8, 10, 12].map(n => (
                        <option key={n} value={n}>
                          {n === 1 ? '1 Step (Full Payment)' : `${n} Installments (Stagered Steps)`}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-gray-600 mb-1.5">Submission Timeline (Interval) *</label>
                    <select
                      value={feeForm.submissionTime}
                      onChange={e => setFeeForm(f => ({ ...f, submissionTime: e.target.value }))}
                      className="input text-xs"
                      required
                    >
                      <option>Monthly</option>
                      <option>Quarterly</option>
                      <option>Semiannually</option>
                      <option>One-time / Termly</option>
                    </select>
                  </div>

                  {/* Dynamic Components Breakdown */}
                  <div className="border-t border-gray-100 pt-4">
                    <div className="flex justify-between items-center mb-2">
                      <label className="block text-xs font-bold text-gray-500 uppercase">Fee Components Breakdown (Optional)</label>
                      {feeComponents.length < 8 && (
                        <button
                          type="button"
                          onClick={() => setFeeComponents([...feeComponents, { id: Date.now() + Math.random(), category: 'Tuition Fee', amount: '' }])}
                          className="text-2xs font-semibold text-blue-600 hover:underline"
                        >
                          + Add Component
                        </button>
                      )}
                    </div>

                    {feeComponents.map((c, idx) => (
                      <div key={c.id} className="flex gap-2 items-center mb-2">
                        <select
                          value={c.category}
                          onChange={e => {
                            const updated = feeComponents.map((item, i) => i === idx ? { ...item, category: e.target.value } : item);
                            setFeeComponents(updated);
                          }}
                          className="input text-xs py-1.5 flex-1"
                        >
                          <option>Tuition Fee</option>
                          <option>Exam Fee</option>
                          <option>Extra Classes Fee</option>
                          <option>Computer Classes Fee</option>
                          <option>Library Fee</option>
                          <option>Sports Fee</option>
                          <option>Transport Fee</option>
                          <option>Other Fee</option>
                        </select>
                        <input
                          type="number"
                          placeholder="Amount"
                          value={c.amount}
                          onChange={e => {
                            const updated = feeComponents.map((item, i) => i === idx ? { ...item, amount: e.target.value } : item);
                            setFeeComponents(updated);
                          }}
                          className="input text-xs py-1.5 w-24"
                          required
                        />
                        <button
                          type="button"
                          onClick={() => {
                            const updated = feeComponents.filter((_, i) => i !== idx);
                            setFeeComponents(updated);
                          }}
                          className="p-1.5 text-red-500 hover:bg-red-50 rounded"
                        >
                          ✖
                        </button>
                      </div>
                    ))}

                    {feeComponents.length > 0 && (
                      <div className="mt-2 p-2 bg-gray-50 rounded-xl text-xxs font-medium space-y-1">
                        <div className="flex justify-between text-gray-500">
                          <span>Sum of Components:</span>
                          <span className="font-bold text-primary">₹ {sumComponents.toLocaleString()}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Unassigned Balance:</span>
                          <span className={`font-bold ${unassignedAmount === 0 ? 'text-green-600' : 'text-amber-600'}`}>
                            ₹ {unassignedAmount.toLocaleString()}
                          </span>
                        </div>
                        {Math.abs(unassignedAmount) >= 0.01 && (
                          <p className="text-[10px] text-amber-500 mt-1">⚠️ Sum of components must equal the Total Amount (difference must be 0).</p>
                        )}
                      </div>
                    )}
                  </div>

                  <button
                    type="submit"
                    disabled={loadingFees || !isBreakdownValid}
                    className={`w-full btn-primary justify-center font-bold text-xs py-3 rounded-xl transition-all ${(!isBreakdownValid) ? 'opacity-50 cursor-not-allowed' : ''
                      }`}
                  >
                    {loadingFees ? 'Creating rule...' : 'Apply & Generate Invoices'}
                  </button>
                </form>
              </div>

              {/* Active Fee Setup Rules List */}
              <div className="card col-span-2">
                <h3 className="font-display font-bold text-primary text-lg mb-2 flex items-center gap-2">
                  📋 Configured Fee Rules
                </h3>
                <p className="text-gray-400 text-xs mb-4">View and delete established fee rules. Deleting a rule deletes any unpaid stagered invoices associated with it.</p>

                <div className="overflow-x-auto">
                  <table className="w-full text-left">
                    <thead>
                      <tr className="border-b border-gray-100">
                        <th className="py-2 text-xs font-bold text-gray-500 uppercase min-w-[150px]">Rule Description</th>
                        <th className="py-2 text-xs font-bold text-gray-500 uppercase min-w-[120px]">Scope / Target</th>
                        <th className="py-2 text-xs font-bold text-gray-500 uppercase min-w-[100px]">Total Amount</th>
                        <th className="py-2 text-xs font-bold text-gray-500 uppercase min-w-[80px]">Steps</th>
                        <th className="py-2 text-xs font-bold text-gray-500 uppercase min-w-[120px]">Timeline</th>
                        <th className="py-2 text-xs font-bold text-gray-500 uppercase text-right w-16">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      {feeRules.map(fr => (
                        <tr key={fr.id} className="border-b border-gray-50 hover:bg-gray-50">
                          <td className="py-3 text-sm font-semibold text-primary">
                            <div className="font-semibold text-sm">{fr.name}</div>
                            {fr.breakdown && (() => {
                              try {
                                const parsed = JSON.parse(fr.breakdown);
                                if (!Array.isArray(parsed)) return null;
                                return (
                                  <div className="mt-1 flex flex-wrap gap-1">
                                    {parsed.map((item, idx) => (
                                      <span key={idx} className="inline-block px-2 py-0.5 bg-primary/5 text-primary text-[10px] font-bold rounded-lg border border-primary/10">
                                        {item.category}: ₹ {Number(item.amount || 0).toLocaleString()}
                                      </span>
                                    ))}
                                  </div>
                                );
                              } catch (e) {
                                return null;
                              }
                            })()}
                          </td>
                          <td className="py-3 text-sm text-gray-600 font-medium">
                            {fr.studentName ? (
                              <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-3xs font-bold bg-blue-50 text-blue-700 border border-blue-100">
                                👤 {fr.studentName}
                              </span>
                            ) : (
                              <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-3xs font-bold bg-primary/5 text-primary border border-primary/10">
                                🏫 {fr.grade}
                              </span>
                            )}
                          </td>
                          <td className="py-3 text-sm font-bold text-gray-700">₹ {Number(fr.amount || 0).toLocaleString()}</td>
                          <td className="py-3 text-sm font-semibold text-primary">{fr.installments} {fr.installments === 1 ? 'step' : 'steps'}</td>
                          <td className="py-3 text-sm text-gray-400 font-medium">{fr.submissionTime}</td>
                          <td className="py-3 text-sm text-right">
                            <button
                              onClick={() => handleDeleteFeeRule(fr.id)}
                              disabled={loadingFees}
                              className="p-1 text-rose-500 hover:text-rose-700 hover:bg-rose-50 rounded transition-colors"
                              title="Delete Fee Rule"
                            >
                              <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                              </svg>
                            </button>
                          </td>
                        </tr>
                      ))}
                      {feeRules.length === 0 && (
                        <tr>
                          <td colSpan="6" className="text-center py-6 text-gray-400 text-xs">No fee setup rules defined yet.</td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          );
    </>
  );
};

export default FeeRulesTab;
